<a href="https://colab.research.google.com/github/blackswords/sashi-pritam-portfolio/blob/main/Visualize_YouTube_Data_with_Plotly_Express_ip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.11.11

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving most_subscribed_youtube_channels.csv to most_subscribed_youtube_channels.csv

In [ ]:
import pandas as pd
import io

In [ ]:
import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels.csv']))
display(df)

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,T-Series,"222,000,000","198,459,090,822","17,317",Music,2006
1,2,YouTube Movies,"154,000,000",0,0,Film & Animation,2015
2,3,Cocomelon - Nursery Rhymes,"140,000,000","135,481,339,848",786,Education,2006
3,4,SET India,"139,000,000","125,764,252,686","91,271",Shows,2006
4,5,Music,"116,000,000",0,0,NaN,2013
...,...,...,...,...,...,...,...
995,996,JP Plays,"10,900,000","4,609,300,218","3,528",Gaming,2014
996,997,TrapMusicHDTV,"10,900,000","4,070,521,973",690,Music,2013
997,998,Games EduUu,"10,900,000","3,093,784,767","1,006",Gaming,2011
998,999,Hueva,"10,900,000","3,040,301,750",831,Gaming,2012
999,1000,Dobre Brothers,"10,900,000","2,808,411,693",590,People & Blogs,2017

In [ ]:
df = df.replace(',', '')
display(df)

,rank,Youtuber,subscribers,video views,video count,category,started
0,1,T-Series,"222,000,000","198,459,090,822","17,317",Music,2006
1,2,YouTube Movies,"154,000,000",0,0,Film & Animation,2015
2,3,Cocomelon - Nursery Rhymes,"140,000,000","135,481,339,848",786,Education,2006
3,4,SET India,"139,000,000","125,764,252,686","91,271",Shows,2006
4,5,Music,"116,000,000",0,0,NaN,2013
...,...,...,...,...,...,...,...
995,996,JP Plays,"10,900,000","4,609,300,218","3,528",Gaming,2014
996,997,TrapMusicHDTV,"10,900,000","4,070,521,973",690,Music,2013
997,998,Games EduUu,"10,900,000","3,093,784,767","1,006",Gaming,2011
998,999,Hueva,"10,900,000","3,040,301,750",831,Gaming,2012
999,1000,Dobre Brothers,"10,900,000","2,808,411,693",590,People & Blogs,2017

In [ ]:
import plotly.express as px

In [ ]:
fig = px.histogram(df, x='subscribers', title='Subscriber Count')
fig.show()

In [ ]:
import plotly.express as px

fig = px.box(df, y='started', title='Years Started')
fig.show()

In [ ]:
import plotly.express as px
import pandas as pd
from google.colab import files
uploaded=files.upload()
# Load your CSV file
df = pd.read_csv("most_subscribed_youtube_channels.csv")  # Replace with the correct file path

# Remove hidden spaces from column names
df.columns = df.columns.str.replace('\xa0', '').str.strip()

# Ensure 'subscribers' is numeric
df['subscribers'] = df['subscribers'].astype(str).str.replace(',', '').astype(int)

# Drop rows where 'category' is missing
df_cleaned = df.dropna(subset=['category'])

# Plot the pie chart
fig = px.pie(df_cleaned, values='subscribers', names='category', title="YouTube Categories")
fig.show()

Saving most_subscribed_youtube_channels.csv to most_subscribed_youtube_channels.csv

**K-Means Clustering on YouTube Channels (Unsupervised Learning)**

Group channels into clusters based on subscribers, views, and video count to identify different types of content creators.

**Steps:**
Normalize the data (since subscribers, views, and video count have different scales).
Apply K-Means Clustering (sklearn.cluster.KMeans).
Visualize clusters using a 3D Scatter Plot (Plotly).

**3D Scatter Plot showing clusters of different YouTube channels.**

In [16]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import plotly.express as px

# Load dataset
df = pd.read_csv("most_subscribed_youtube_channels.csv")

# Convert numeric columns (remove commas and convert to integers)
df['subscribers'] = df['subscribers'].str.replace(',', '').astype(float)
df['video views'] = df['video views'].str.replace(',', '').astype(float)
df['video count'] = df['video count'].str.replace(',', '').astype(float)

# Select features and normalize them
features = df[['subscribers', 'video views', 'video count']]
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

# Apply K-Means
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(scaled_features)

# Visualizing in 3D
fig = px.scatter_3d(df, x='subscribers', y='video views', z='video count', color=df['cluster'].astype(str),
                     title="YouTube Channel Clusters", labels={'color': 'Cluster'})
fig.show()

**Time Series Forecasting (ARIMA) for Future Subscriber Growth**

Predict the number of subscribers a top channel will have in the future.
Helps understand growth patterns.
**Steps:**

Select a top channel and retrieve its subscriber count over time.

Use ARIMA (AutoRegressive Integrated Moving Average) from statsmodels to forecast future growth.

Plot actual vs. predicted subscribers over time.

**Line Chart showing actual vs. predicted subscriber growth over time**.

In [15]:
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd

# Aggregate subscribers by year
yearly_data = df.groupby('started')['subscribers'].sum().reset_index()

# Fit ARIMA Model
model = ARIMA(yearly_data['subscribers'], order=(2,1,2))  # (p,d,q) parameters
model_fit = model.fit()

# Predict next 10 years
future_years = [yearly_data['started'].max() + i for i in range(1, 11)]
future_forecast = model_fit.forecast(steps=10)

# Create DataFrame for future predictions
future_df = pd.DataFrame({'started': future_years, 'subscribers': future_forecast})

# Combine actual and predicted data
combined_df = pd.concat([yearly_data, future_df])

# Visualize
fig = px.line(combined_df, x='started', y='subscribers', title="Predicted YouTube Subscriber Growth")
fig.show()

/usr/local/lib/python3.11/dist-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning:

Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.

/usr/local/lib/python3.11/dist-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning:

Non-invertible starting MA parameters found. Using zeros as starting parameters.

**Anomaly Detection in YouTube Data (Isolation Forest)**

Detect unusual YouTube channels with extreme subscriber counts, views, or video counts.

**Steps:**

Use IsolationForest to detect anomalies.

Flag outliers as unusual channels.

Visualize using a scatter plot.

**Scatter Plot where anomalies (extreme YouTube channels) are highlighted.**

In [17]:
from sklearn.ensemble import IsolationForest

# Train Isolation Forest
iso_forest = IsolationForest(contamination=0.02, random_state=42)
df['anomaly'] = iso_forest.fit_predict(df[['subscribers', 'video views', 'video count']])

# Plot anomalies
fig = px.scatter(df, x='subscribers', y='video views', color=df['anomaly'].astype(str),
                 title="Anomaly Detection in YouTube Data", labels={'color': 'Anomaly'})
fig.show()

**Network Graph (Channel Similarity)**

Create a graph network where similar YouTube channels are linked based on shared categories and subscriber count

**Steps:**

Use networkx to build a graph where:

Nodes = YouTube channels

Edges = Channels in the same category with similar subscribers

Use Plotly to visualize the network.

In [19]:
import pandas as pd
import networkx as nx
import plotly.graph_objects as go

# Load dataset (update file path as needed)
df = pd.read_csv("most_subscribed_youtube_channels.csv")

# ✅ Clean column names (remove spaces & convert to lowercase)
df.columns = df.columns.str.strip().str.lower()

# ✅ Print available column names for debugging
print("Columns in dataset:", df.columns)

# ✅ Rename columns if necessary (update based on actual dataset)
column_mapping = {
    'youtuber': 'channel_name',  # Change to actual column name in your CSV
    'category': 'channel_category',
    'subscribers': 'subscriber_count'
}
df = df.rename(columns=column_mapping)

# ✅ Ensure required columns exist
required_cols = ['channel_name', 'channel_category', 'subscriber_count']
for col in required_cols:
    if col not in df.columns:
        raise KeyError(f"Column '{col}' not found in dataset. Check CSV file.")

# ✅ Convert "subscribers" column to numeric (remove commas if present)
df['subscriber_count'] = df['subscriber_count'].astype(str).str.replace(',', '').astype(float)

# ✅ Drop rows with missing values in required columns
df = df.dropna(subset=['channel_name', 'channel_category', 'subscriber_count'])

# ✅ Create Network Graph
G = nx.Graph()

# Add nodes
for _, row in df.iterrows():
    G.add_node(row['channel_name'], size=row['subscriber_count'], category=row['channel_category'])

# Add edges (connect channels in the same category with similar subscribers)
for _, row1 in df.iterrows():
    for _, row2 in df.iterrows():
        if row1['channel_category'] == row2['channel_category'] and abs(row1['subscriber_count'] - row2['subscriber_count']) < 5_000_000:
            G.add_edge(row1['channel_name'], row2['channel_name'])

# Create positions for visualization
pos = nx.spring_layout(G, seed=42)

# Create edge trace
edge_x = []
edge_y = []
for edge in G.edges():
    x0, y0 = pos[edge[0]]
    x1, y1 = pos[edge[1]]
    edge_x.append(x0)
    edge_x.append(x1)
    edge_x.append(None)
    edge_y.append(y0)
    edge_y.append(y1)
    edge_y.append(None)

edge_trace = go.Scatter(x=edge_x, y=edge_y, line=dict(width=0.5, color='#888'), mode='lines')

# Create node trace
node_x = []
node_y = []
node_size = []
node_text = []
for node in G.nodes():
    x, y = pos[node]
    node_x.append(x)
    node_y.append(y)
    node_size.append(G.nodes[node]['size'] / 5_000_000)  # Scale size for better visualization
    node_text.append(f"{node} ({G.nodes[node]['category']})")

node_trace = go.Scatter(
    x=node_x, y=node_y, mode='markers',
    marker=dict(size=node_size, color='blue'),
    text=node_text
)

# Create Plotly figure
fig = go.Figure(data=[edge_trace, node_trace],
                layout=go.Layout(title="YouTube Channel Network Graph",
                                 showlegend=False, hovermode='closest'))

# Show graph
fig.show()

Columns in dataset: Index(['rank', 'youtuber', 'subscribers', 'video views', 'video count',
       'category', 'started'],
      dtype='object')

**Sunburst Chart: Category Breakdown with Sub-Categories**


Shows nested data (Category → Top Creators → Subscribers).
** Steps:**

**Use px.sunburst() to create a multi-level breakdown.**

In [23]:
fig = px.sunburst(df, path=['channel_category', 'channel_name'], values='subscriber_count', title="YouTube Category Breakdown")
fig.show()